### PR TITLE
Using len() to get number of players

### PR DESCRIPTION
**Pull request by zadignose**
The most minor of edits, but it's something.

### CODE REVIEW

**Comment by minhdang118** [comment]
Thank you for the edit!

**Comment by zadignose** [comment]
Glad to help. I've been looking into the possibility of whether the specific rules of a game, such as Texas Hold'em, can be handled by a separate class, but I'm not sure whether it fits with your plans. I'm also a total Noob to GitHub, but if I come up with something that might be of interest, I'll be glad to share it.

**Comment by minhdang118** [comment]
My current plan is to implement Texas Hold'em game rules, then try to implement certain player strategies and simulate them to see whose outcome is the best. Many thanks for your interest and contributions!

**Comment by zadignose** [comment]
Cool.

**Pull request merged**
